import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// ---------------------------------------------------------------------
// Deterministic synthetic seed generator (no Math.random — repeatable).
// Produces docs/data/turso/seed.sql for the Turso/SQLite dev replica.
// All data is fake: @example.test emails, no real PII, numeric person_ids.
// ---------------------------------------------------------------------

const out = resolve(process.cwd(), 'docs', 'data', 'turso', 'seed.sql');
const lines: string[] = [];

lines.push('-- =====================================================================');
lines.push('-- HR Reporting — Turso / SQLite Development Seed (SYNTHETIC DATA)');
lines.push('-- Generated by scripts/generate-turso-seed.mts. Do not hand-edit.');
lines.push('-- No real PII: all names/emails/IDs are fabricated for offline dev/demo.');
lines.push('-- =====================================================================');
lines.push('');
lines.push('PRAGMA foreign_keys = OFF;');
lines.push('BEGIN;');
lines.push('');

const sql = (s: string) => lines.push(s);

const esc = (v: string | number | null): string => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

// ----- Schools (school_no, school_name, level, region) -----
const schools = [
  { no: '0302', name: 'Test Oak Elementary', level: 'Elementary School', region: 'Central' },
  { no: '0340', name: 'Test Maple Middle', level: 'Middle School', region: 'North' },
  { no: '0501', name: 'Test River High', level: 'High School', region: 'South' },
  { no: '9900', name: 'Test Central Office', level: 'Central Office', region: 'District' },
  { no: '0455', name: 'Test Cedar Elementary', level: 'Elementary School', region: 'North' }
];

sql('-- schools');
for (const s of schools) {
  sql(`INSERT INTO schools (school_no, school_name, school_level, school_region, administrator, calendar, FLEX_VALUE_SET_ID, FLEX_VALUE_ID, FLEX_VALUE, address_1, City, State, Zip, Magnet) VALUES (` +
    `${esc(s.no)}, ${esc(s.name)}, ${esc(s.level)}, ${esc(s.region)}, ${esc('Principal ' + s.no)}, ${esc('Standard')}, ` +
    `${esc('101')}, ${esc(s.no)}, ${esc(s.no)}, ${esc('1 Test Way')}, ${esc('Testville')}, ${esc('NC')}, ${esc('27700')}, ${esc('No')});`);
}

const classroomValues = ['English', 'Mathematics', 'Science', 'Spanish', 'French', 'Social Studies', 'Biology', 'Counselor', 'ESL', 'Digital Media', 'None Assigned'] as const;

const roleMonths: Record<string, number> = {
  'Teacher': 10,
  'Assistant Principal': 11,
  'Principal': 12,
  'Counselor': 11,
  'Data Analyst': 12,
  'HR Specialist': 12,
  'Admin': 11,
  'Analyst': 12
};

// pos_start: deterministic date 10-12 years ago (2014-09-05 to 2016-09-05) so
// every position looks like it was created when the school was built.
function posStartFor(idx: number, id: number): string {
  const startMs = Date.UTC(2014, 8, 5); // 2014-09-05
  const rangeDays = 731; // inclusive range to 2016-09-05
  const offsetDays = (idx * 37 + id * 13) % rangeDays;
  const ms = startMs + offsetDays * 24 * 60 * 60 * 1000;
  const d = new Date(ms);
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

// ----- People (employee_info) -----
// person_id is numeric so it aligns with cert_info/position_info INTEGER keys.
// pos is assigned deterministically after all people are collected to ensure uniqueness (no duplicates).
const peopleBase: Array<{ id: number; first: string; last: string; org: string; role: string; qual: string }> = [
  { id: 10001, first: 'Alex', last: 'Example', org: 'Test Oak Elementary', role: 'Teacher', qual: 'Teacher' },
  { id: 10002, first: 'Jordan', last: 'Sample', org: 'Test Oak Elementary', role: 'Principal', qual: 'Principal' },
  { id: 10003, first: 'Taylor', last: 'Fixture', org: 'Test Oak Elementary', role: 'Assistant Principal', qual: 'Admin' },
  { id: 10004, first: 'Morgan', last: 'Case', org: 'Test Oak Elementary', role: 'Teacher', qual: 'Teacher' },
  { id: 10005, first: 'Casey', last: 'Doe', org: 'Test Oak Elementary', role: 'Teacher', qual: 'Teacher' },
  { id: 10006, first: 'Riley', last: 'Smith', org: 'Test Maple Middle', role: 'Teacher', qual: 'Teacher' },
  { id: 10007, first: 'Avery', last: 'Jones', org: 'Test Maple Middle', role: 'Counselor', qual: 'Counselor' },
  { id: 10008, first: 'Quinn', last: 'Brown', org: 'Test Maple Middle', role: 'Teacher', qual: 'Teacher' },
  { id: 10009, first: 'Drew', last: 'Davis', org: 'Test River High', role: 'Teacher', qual: 'Teacher' },
  { id: 10010, first: 'Peyton', last: 'Miller', org: 'Test River High', role: 'Principal', qual: 'Principal' },
  { id: 10011, first: 'Reese', last: 'Wilson', org: 'Test River High', role: 'Teacher', qual: 'Teacher' },
  { id: 10012, first: 'Jamie', last: 'Moore', org: 'Test Central Office', role: 'Data Analyst', qual: 'Analyst' },
  { id: 10013, first: 'Charlie', last: 'Taylor', org: 'Test Central Office', role: 'HR Specialist', qual: 'Analyst' },
  { id: 10014, first: 'Skyler', last: 'Anderson', org: 'Test Cedar Elementary', role: 'Teacher', qual: 'Teacher' },
  { id: 10015, first: 'Rowan', last: 'Thomas', org: 'Test Cedar Elementary', role: 'Teacher', qual: 'Teacher' }
];

// Add more teachers to bulk up base data.
const extraNames = [
  ['Aiden', 'Clark'], ['Liam', 'Lewis'], ['Noah', 'Walker'], ['Ethan', 'Hall'],
  ['Mason', 'Allen'], ['Logan', 'Young'], ['James', 'King'], ['Lucas', 'Wright'],
  ['Henry', 'Scott'], ['Jack', 'Torres'], ['Owen', 'Nguyen'], ['Wyatt', 'Hill'],
  ['Levi', 'Flores'], ['Isaac', 'Green'], ['Dylan', 'Adams'], ['Luke', 'Nelson'],
  ['Carter', 'Baker'], ['Jayden', 'Rivera'], ['Eli', 'Campbell'], ['Caleb', 'Mitchell']
];
const teacherOrgs = ['Test Oak Elementary', 'Test Maple Middle', 'Test River High', 'Test Cedar Elementary'] as const;
for (let i = 0; i < extraNames.length; i++) {
  const [first, last] = extraNames[i];
  const org = teacherOrgs[i % teacherOrgs.length];
  peopleBase.push({ id: 10016 + i, first, last, org, role: 'Teacher', qual: 'Teacher' });
}
// 10 extra non-matching demo rows for Contract Report (tap=1, contract_id set, but desc/code avoid highlight filters)
const nonMatchingNames = [
  ['Harper', 'Bennett'], ['Evelyn', 'Cole'], ['Grace', 'Reed'], ['Chloe', 'Murphy'], ['Ava', 'Cooper'],
  ['Sophia', 'Bell'], ['Isabella', 'Ward'], ['Mia', 'Price'], ['Lily', 'Howard'], ['Zoe', 'Foster']
];
for (let i = 0; i < nonMatchingNames.length; i++) {
  const [first, last] = nonMatchingNames[i];
  peopleBase.push({ id: 10036 + i, first, last, org: 'Test Oak Elementary', role: 'Teacher', qual: 'Teacher' });
}

// Assign unique pos_number per person: 3180101, 3180102, ... (no duplicates, deterministic)
const people = peopleBase.map((p, idx) => ({ ...p, pos: 3180101 + idx }));

// Build position_info from people — one unique position per employee (no duplicates)
const positions = people.map((p, idx) => ({
  id: 1001 + idx,
  number: p.pos,
  name: p.role,
  org: p.org,
  months: roleMonths[p.role] ?? 10
}));
const posByNumber = new Map(positions.map((p) => [p.number, p]));

// Mapping per docs/columns/mapping.md: contract_type <-> contract_desc (tenure_desc)
const contractMapping = [
  { type: 'T', desc: 'Terminating' },
  { type: 'NC', desc: 'No Contract' },
  { type: '1Y', desc: 'One Year Contract' },
  { type: '2Y', desc: 'Two Year Contract' },
  { type: 'C', desc: 'Career Contract' },
  { type: '4E', desc: '' }
] as const;
const safeMapping = [
  { type: '1Y', desc: 'One Year Contract' },
  { type: '2Y', desc: 'Two Year Contract' },
  { type: 'C', desc: 'Career Contract' }
] as const;
// Same selection logic as the employee_info loop (non-matching demo rows use safeMapping).
function contractTypeFor(id: number): string {
  const isNonMatchingDemo = id >= 10036;
  const mapping = isNonMatchingDemo
    ? safeMapping[id % safeMapping.length]
    : contractMapping[id % contractMapping.length];
  return mapping.type;
}
// Position Details "Pos. ending" cleanup: derive POS. ENDING from the incumbent's
// CONTRACT_ID / contract_type code. Per user spec: "has a 1" (1Y) -> 2027, "has a 2"
// (2Y) -> 2028; Career (C) -> 2030; every other code (T, NC, 4E) -> 2029.
function posEndingFor(contractType: string): string {
  switch (contractType) {
    case '1Y': return '2027-06-30';
    case '2Y': return '2028-06-30';
    case 'C': return '2030-06-30';
    default: return '2029-06-30'; // T, NC, 4E
  }
}

sql('-- position_info');
for (let i = 0; i < positions.length; i++) {
  const p = positions[i];
  const posStart = posStartFor(i, p.id);
  const person = people[i];
  const contractType = contractTypeFor(person.id);
  const posEnding = posEndingFor(contractType);
  sql(`INSERT INTO position_info (position_id, pos_number, pos_name, organization, months, fund, object, cost_center, level, administrator, calendar, loc_type, region, ss200_code, pos_start, pos_ending) VALUES (` +
    `${p.id}, ${p.number}, ${esc(p.name)}, ${esc(p.org)}, ${p.months}, ${esc('01')}, ${esc('120')}, ${esc('0901')}, ${esc('LEVEL')}, ${esc('Principal ' + p.org.toUpperCase())}, ${esc('Standard')}, ${esc('S')}, ${esc('Central')}, ${esc('SS200')}, ${esc(posStart)}, ${esc(posEnding)});`);
}

// ----- position_info: VACANT positions (no matching employee_info row) -----
// These exercise the Position Details drawer's vacant path — a position that
// exists in position_info but has no incumbent in employee_info.
sql('-- position_info: vacant positions');
const vacantPositions = [
  { id: 2001, number: 3180301, name: 'Teacher', org: 'Test Oak Elementary', months: 10 },
  { id: 2002, number: 3180302, name: 'Assistant Principal', org: 'Test Maple Middle', months: 11 },
  { id: 2003, number: 3180303, name: 'Counselor', org: 'Test River High', months: 11 },
  { id: 2004, number: 3180304, name: 'Teacher', org: 'Test Cedar Elementary', months: 10 },
  { id: 2005, number: 3180305, name: 'HR Specialist', org: 'Test Central Office', months: 12 }
];
for (let i = 0; i < vacantPositions.length; i++) {
  const p = vacantPositions[i];
  const posStart = posStartFor(i + positions.length, p.id);
  sql(`INSERT INTO position_info (position_id, pos_number, pos_name, organization, months, fund, object, cost_center, level, administrator, calendar, loc_type, region, ss200_code, pos_start, pos_ending) VALUES (` +
    `${p.id}, ${p.number}, ${esc(p.name)}, ${esc(p.org)}, ${p.months}, ${esc('01')}, ${esc('120')}, ${esc('0901')}, ${esc('LEVEL')}, ${esc('Principal ' + p.org.toUpperCase())}, ${esc('Standard')}, ${esc('S')}, ${esc('Central')}, ${esc('SS200')}, ${esc(posStart)}, ${esc('0000-00-00')});`);
}

sql('-- employee_info');
const contractTapIds = new Set([10001, 10002, 10003, 10004, 10005, 10016, 10020, 10036, 10037, 10038, 10039, 10040, 10041, 10042, 10043, 10044, 10045]);
const contractCodes = ['2027', '2028', '2029', '2030', '3000', '9999'] as const;
const safeCodes = ['2028', '2029', '2030', '3000', '9999'] as const;
for (const p of people) {
  const fullName = `${p.last}, ${p.first}`;
  const empNo = `9${String(p.id).slice(-5)}`;
  const email = `${p.first.toLowerCase()}.${p.last.toLowerCase()}@example.test`;
  const hireYear = 2010 + (p.id % 15);
  const hireDate = `${hireYear}-08-15`;
  const step = (p.id % 10) + 1;
  const salary = 40000 + (p.id % 25) * 1000;
  const tenure = p.id % 12;
  const dob = esc(`198${p.id % 9 == 0 ? 8 : p.id % 9}-0${(p.id % 9) + 1}-1${p.id % 9}`);
  const renewalStart = esc(`${2026 - (p.id % 3)}-07-01`);
  const isContractTap = contractTapIds.has(p.id);
  const tapValue = isContractTap ? 1 : 100;
  const isNonMatchingDemo = p.id >= 10036;
  const mapping = isNonMatchingDemo ? safeMapping[p.id % safeMapping.length] : contractMapping[p.id % contractMapping.length];
  const tenureDescVal = mapping.desc;
  const contractTypeVal = mapping.type;
  // contract_id always carries the contract type code so the Staff Planning
  // report's contract_id column is never blank for a filled position.
  const contractIdValue = esc(contractTypeVal);
  const contractTypeColVal = esc(contractTypeVal);
  let tenureCodeVal = isNonMatchingDemo ? safeCodes[p.id % safeCodes.length] : contractCodes[p.id % contractCodes.length];
  // Real-data accuracy: rows whose contract_desc is "Terminating" carry contract code 9999.
  if (tenureDescVal === 'Terminating') {
    tenureCodeVal = '9999';
  }
  // Demo accuracy: rows whose contract_type is "1Y" (One Year Contract) carry contract code 2027.
  if (contractTypeVal === '1Y') {
    tenureCodeVal = '2027';
  }
  const contractEndValue = esc(p.id === 10016 || p.id === 10020 ? '2028-06-30' : '2027-06-30');
  const classroomVal = classroomValues[p.id % classroomValues.length];
  sql(`INSERT INTO employee_info (` +
    `person_id, emp_number, first_name, middle_name, last_name, full_name, e_mail, personal_email, ` +
    `organization, pos_name, position_id, pos_number, classroom_assignment, cost_center, object, account_code, ` +
    `primary_flag, assignment_status, assignment_number, category, group1, pay_grade, a_months, tap, mailstop, ` +
    `sex, ethnicity, dob, title, tenure_code, tenure_desc, loc_type, person_type, region, administrator, calendar, ` +
    `pay_basis, step, proposed_salary, fixed_supplement, off_scale, supp_rate, monthly_supplement, normal_hours, ` +
    `TOS_State, AP_Teacher_Diff, hire_date, continuous_service_date, last_change, last_updated, contract_type, contract_id, ` +
    `contract_start, contract_end, renewal_start, renewal_end, change_type, board_number, certification_type, ` +
    `cert_areas, license_expiration, nbpts_expire, years_of_serv, months_of_serv) VALUES (` +
    `${p.id}, ${esc(empNo)}, ${esc(p.first)}, ${esc('')}, ${esc(p.last)}, ${esc(fullName)}, ${esc(email)}, ${esc(`${p.first.toLowerCase()}.personal@example.test`)}, ` +
    `${esc(p.org)}, ${esc(p.role)}, ${esc(String(p.pos))}, ${esc(String(p.pos))}, ${esc(classroomVal)}, ${esc('0901')}, ${esc('120')}, ${esc('01.0000.000.000.0001')}, ` +
    `${esc('Y')}, ${esc('Active')}, ${esc('A-' + empNo)}, ${esc('Instructional Staff')}, ${esc(p.qual + ' Staff')}, ${esc(p.qual)}, ${10}, ${tapValue}, ${esc('MS-' + p.id % 999)}, ` +
    `${esc(p.id % 2 === 0 ? 'F' : 'M')}, ${esc('Not specified')}, ${dob}, ${esc(p.role)}, ${esc(tenureCodeVal)}, ${esc(tenureDescVal)}, ` +
    `${esc('S')}, ${esc('Employee')}, ${esc('Central')}, ${esc('Principal ' + p.org.toUpperCase())}, ${esc('Standard')}, ` +
    `${esc('Monthly')}, ${step}, ${salary}, 0, ${esc('N')}, 0, 0, 40, ` +
    `${p.id % 3 === 0 ? 1500 : 0}, ${p.id % 4 === 0 ? 1000 : 0}, ${esc(hireDate)}, ${esc(hireDate)}, ${renewalStart}, ${esc('2026-08-31')}, ${contractTypeColVal}, ${contractIdValue}, ` +
    `${esc('2026-08-01')}, ${contractEndValue}, ${esc('2026-07-01')}, ${esc('2027-06-30')}, ${esc('Annual update')}, ${esc('BOARD-' + p.id)}, ${esc('Regular')}, ` +
    `${esc('00025')}, ${esc('2029-06-30')}, ${esc('2030-06-30')}, ${tenure}, ${(p.id % 9) + 1});`);
}

// ----- schools_example mirrors schools (PK on school_no) -----
sql('-- schools_example');
for (const s of schools) {
  sql(`INSERT INTO schools_example (school_no, school_name, school_level, school_region, administrator, calendar, FLEX_VALUE_SET_ID, FLEX_VALUE_ID, FLEX_VALUE, City, State, Zip) VALUES (` +
    `${esc(s.no)}, ${esc(s.name)}, ${esc(s.level)}, ${esc(s.region)}, ${esc('Principal ' + s.no)}, ${esc('Standard')}, ${esc('101')}, ${esc(s.no)}, ${esc(s.no)}, ${esc('Testville')}, ${esc('NC')}, ${esc('27700')});`);
}

// ----- cert_info (person_id INTEGER) -----
sql('-- cert_info');
for (const p of people) {
  const exp = 2028 + (p.id % 4);
  sql(`INSERT INTO cert_info (person_id, socsec, cert_type_code, certification_type, information_as_of, last_cert_issued, cert_effect, cert_expiration, renewal_start, renewal_end) VALUES (` +
    `${p.id}, ${esc('000-00-' + String(p.id).slice(-3))}, ${esc('REG')}, ${esc('Regular')}, ${esc('2026-08-31')}, ${esc('2025-07-01')}, ${esc('2025-07-01')}, ${esc(`${exp}-06-30`)}, ${esc('2026-07-01')}, ${esc(`${exp}-06-30`)});`);
}

// ----- cert_area (person_id TEXT) -----
// NCLB values sourced from docs/columns/col-values.md (the full descriptive text).
const nclbValues = [
  '82 - Highly Qualified - NC HOUSSE standard',
  '84 - Highly Qualified - masters level licensure or above',
  '86 - Highly Qualified - Other State licensing test(s)',
  '88 - Highly Qualified - coursework = undergrad. major',
  '87 - Highly Qualified - NC Licensing test(s)',
  '97 - Highly Qualified not determined',
  '98 - Not Applicable for Non-Core Academic Areas',
  '99 - Not Highly Qualified'
] as const;

// Certification area catalog (real DPI area codes + descriptions).
// A person may hold MULTIPLE certifications, so each person gets a
// deterministic 1–3 area rows (some single-area, some multi-area).
const certAreaCatalog = [
  { area: '00011', desc: 'School Administrator-Superintendent' },
  { area: '00012', desc: 'School Administrator-Principal' },
  { area: '00025', desc: 'Elementary Grades K-6' },
  { area: '00113', desc: 'Curriculum Instructional Specialist' },
  { area: '00400', desc: 'Social Studies 9-12' },
  { area: '78180', desc: 'Language Arts 6-9' },
  { area: '78300', desc: 'Science 6-9' },
  { area: '78400', desc: 'Social Studies 6-9' }
] as const;

sql('-- cert_area');
for (const p of people) {
  const startIndex = p.id % certAreaCatalog.length;
  const areaCount = 1 + (p.id % 3); // 1..3 areas per person (deterministic)
  for (let k = 0; k < areaCount; k++) {
    const entry = certAreaCatalog[(startIndex + k) % certAreaCatalog.length];
    const nclb = nclbValues[(p.id + k) % nclbValues.length];
    const years = (p.id % 30) + k + 1;
    sql(`INSERT INTO cert_area (person_id, socsec, area, area_description, years, effective, status, basis, class, start_date, NCLB) VALUES (` +
      `${esc(String(p.id))}, ${esc('000-00-' + String(p.id).slice(-3))}, ${esc(entry.area)}, ${esc(entry.desc)}, ${years}, ${esc('2026-08-01')}, ${esc('04')}, ${esc('02')}, ${esc('CLASS')}, ${esc('2019-08-15')}, ${esc(nclb)});`);
  }
}

// ----- address (person_id TEXT) -----
sql('-- address');
for (const p of people) {
  sql(`INSERT INTO address (person_id, address, city, state, zip, phone, ss_mobile, ss_home, ss_work, ss_work_mobile) VALUES (` +
    `${esc(String(p.id))}, ${esc(`${100 + p.id % 900} Example Street`)}, ${esc('Testville')}, ${esc('NC')}, ${esc(`${27000 + p.id % 100}`)}, ${esc(`555-01${String(p.id).slice(-2)}`)}, ${esc('555-0100')}, ${esc('555-0101')}, ${esc('555-0102')}, ${esc('555-0103')});`);
}

// ----- leaves (person_id TEXT; PTO plan names) -----
const leavePlans = [
  { plan: 'PTO Absence Bonus Annual', bal: 0, rate: 0, carry: 0, accrued: 0, used: 0, adj: 0 },
  { plan: 'PTO Annual Leave', bal: 14.09, rate: 4.09, carry: 12, accrued: 4.09, used: 2, adj: 0 },
  { plan: 'PTO Sick Leave', bal: 83.09, rate: 4.09, carry: 80, accrued: 4.09, used: 1, adj: 0 },
  { plan: 'PTO Community Leave', bal: 3, rate: 0, carry: 3, accrued: 0, used: 0, adj: 0 },
  { plan: 'PTO Personal Leave', bal: 12, rate: 1.5, carry: 8, accrued: 4, used: 0, adj: 0 },
  { plan: 'PTO Annual Leave', bal: 30.5, rate: 5.5, carry: 25, accrued: 5.5, used: 0, adj: 0 }
];
sql('-- leaves');
for (const p of people) {
  const plans = leavePlans.filter((_, i) => i <= (p.id % 4));
  for (const lp of plans) {
    sql(`INSERT INTO leaves (person_id, assignment_id, accrual_plan, ytd_accrual_balance, MaxOfaccrual_rate, Carryover, SumOfytd_accrued, SumOfytd_used, SumOfadjustments, MaxOfperiod_end_date, full_name) VALUES (` +
      `${esc(String(p.id))}, ${esc('A-' + String(p.id))}, ${esc(lp.plan)}, ${lp.bal}, ${lp.rate}, ${lp.carry}, ${lp.accrued}, ${lp.used}, ${lp.adj}, ${esc('2026-08-31')}, ${esc(`${p.last}, ${p.first}`)});`);
  }
}

// ----- education_info (person_id TEXT) -----
sql('-- education_info');
for (const p of people) {
  sql(`INSERT INTO education_info (person_id, socsec, education_level, graduation_date, school, state, field, type_degree, gpa, degree) VALUES (` +
    `${esc(String(p.id))}, ${esc('000-00-' + String(p.id).slice(-3))}, ${esc('Masters')}, ${esc('2015-05-20')}, ${esc('Test University')}, ${esc('NC')}, ${esc('Education')}, ${esc('MA')}, 3.8, ${esc('M.Ed')});`);
}

// ----- mentor (PERSON_ID TEXT) -----
sql('-- mentor');
for (const p of people.filter((_, i) => i % 5 === 0)) {
  sql(`INSERT INTO mentor (PERSON_ID, Mentor, Cert_Areas, BT_Status, Mentor_Eligible_for_Pay, BT_Start, BT_End) VALUES (` +
    `${esc(String(p.id))}, ${esc('Yes')}, ${esc('00025')}, ${esc('Active')}, ${esc('Yes')}, ${esc('2025-08-01')}, ${esc('2026-06-30')});`);
}

// ----- resignations (person_id TEXT; a few terminated) -----
sql('-- resignations');
for (const p of people.filter((_, i) => i % 12 === 0)) {
  sql(`INSERT INTO resignations (full_name, title, last_name, first_name, emp_number, TAP, organization, pos_name, assignment_id, person_id, actual_term_date, term_month, term_year, leaving_reason, change_reason, hire_date, region, administrator) VALUES (` +
    `${esc(`${p.last}, ${p.first}`)}, ${esc(p.role)}, ${esc(p.last)}, ${esc(p.first)}, ${esc('9' + String(p.id).slice(-5))}, 100, ${esc(p.org)}, ${esc(p.role)}, ${esc('A-' + p.id)}, ${esc(String(p.id))}, ${esc('2026-06-30')}, ${esc('06')}, ${esc('2026')}, ${esc('Personal')}, ${esc('Resignation')}, ${esc('2015-08-15')}, ${esc('Central')}, ${esc('Principal ' + p.org.toUpperCase())});`);
}

// ----- employee_info_future (vacant future positions; person_id INTEGER) -----
// Vacant rows: blank employee fields, populated position + Last_Person*/Result_Type.
sql('-- employee_info_future (vacant positions + future hires)');
const futureRows = [
  { posName: 'Teacher', number: 3180201, org: 'Test Oak Elementary', personId: null, result: 1, lastNum: 10001, lastName: 'Example, Alex' },
  { posName: 'Counselor', number: 3180202, org: 'Test Maple Middle', personId: null, result: 2, lastNum: 10007, lastName: 'Jones, Avery' },
  { posName: 'Teacher', number: 3180203, org: 'Test River High', personId: null, result: 0, lastNum: null, lastName: null },
  { posName: 'Teacher', number: 3180204, org: 'Test Cedar Elementary', personId: 10016, result: 3, lastNum: null, lastName: null },
  { posName: 'Data Analyst', number: 3180205, org: 'Test Central Office', personId: null, result: 1, lastNum: 10012, lastName: 'Moore, Jamie' }
];
for (const f of futureRows) {
  sql(`INSERT INTO employee_info_future (` +
    `person_id, pos_name, pos_number, organization, full_name, first_name, last_name, title, assignment_status, category, step, a_months, tap, ` +
    `start_date, end_date, Last_PersonNum_In_Position, Last_PersonNAME_In_Position, Result_Type) VALUES (` +
    `${f.personId ?? 0}, ${esc(f.posName)}, ${f.number}, ${esc(f.org)}, ${esc(f.lastName ?? '')}, ${esc('')}, ${esc('')}, ${esc(f.posName)}, ` +
    `${esc('Vacant')}, ${esc('Instructional Staff')}, ${5}, ${10}, 100, ` +
    `${esc('2026-01-01')}, ${esc('2026-06-30')}, ${f.lastNum ?? 'NULL'}, ${esc(f.lastName ?? '')}, ${f.result});`);
}

// ----- assignment (person_id TEXT) -----
sql('-- assignment');
for (const p of people) {
  const classroomVal = classroomValues[p.id % classroomValues.length];
  sql(`INSERT INTO assignment (assign_id, person_id, position_id, assign_start, assign_end, tap, classroom_assignment, "primary", category, "group", pay_grade, change_type, assignment_status, full_name) VALUES (` +
    `${esc('A-' + p.id)}, ${esc(String(p.id))}, ${esc(String(p.pos))}, ${esc('2026-08-01')}, ${esc('2027-06-30')}, 100, ${esc(classroomVal)}, ${esc('Y')}, ${esc('Instructional Staff')}, ${esc(p.qual + ' Staff')}, ${esc(p.qual)}, ${esc('Annual update')}, ${esc('Active')}, ${esc(`${p.last}, ${p.first}`)});`);
}

// ----- s_n_a (summary projection) -----
sql('-- s_n_a');
for (const s of schools) {
  sql(`INSERT INTO s_n_a ("Object Category", Employees, Age, NBPTS, Masters, "< 5 Yrs", "25+ Yrs", Hires, "Mon Hires", "Resign Year", "Resign Month", Updated) VALUES (` +
    `${esc(s.name)}, ${100 + s.no.charCodeAt(1)}, 38, 12, 45, 8, 5, 3, 2, 6, 6, ${esc('2026-08-31')});`);
}

lines.push('COMMIT;');
lines.push('');
lines.push('-- Done. Synthetic seed loaded.');

writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`Wrote ${out} (${lines.length} lines).`);
